### ISSUE TITLE
Error with docker-compose

### ISSUE THREAD

**Issue by pdcmoreira** [opsxcq/docker-mopidy#3]
Hi, I'm trying to run this in docker-compose, but I'm getting an error.

My services are:
```yaml
  mopidy:
    image: strm/mopidy
    ports:
      - 6600:6600
      - 6680:6680
    volumes:
      - /data/media/music:/music
      - /tmp/audio-output:/output

  snapcast:
    image: strm/snapcast
    ports:
      - 1704:1704
    volumes:
      - /tmp/audio-output:/output
```

Snapcast is up, but mopidy is not.

Trying to run the mopidy service individually:
`sudo docker-compose up mopidy`

I get this error:
```
mopidy_1         | libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Operation not permitted
mopidy_1         | libdc1394 error: Failed to initialize libdc1394
mopidy_1         | Traceback (most recent call last):
mopidy_1         |   File "/usr/bin/mopidy", line 11, in <module>
mopidy_1         |     load_entry_point('Mopidy==2.2.1', 'console_scripts', 'mopidy')()
mopidy_1         |   File "/usr/lib/python2.7/dist-packages/mopidy/__main__.py", line 61, in main
mopidy_1         |     create_core_dirs(config)
mopidy_1         |   File "/usr/lib/python2.7/dist-packages/mopidy/__main__.py", line 147, in create_core_dirs
mopidy_1         |     path.get_or_create_dir(config['core']['cache_dir'])
mopidy_1         |   File "/usr/lib/python2.7/dist-packages/mopidy/internal/path.py", line 31, in get_or_create_dir
mopidy_1         |     os.makedirs(dir_path, 0o755)
mopidy_1         |   File "/usr/lib/python2.7/os.py", line 150, in makedirs
mopidy_1         |     makedirs(head, mode)
mopidy_1         |   File "/usr/lib/python2.7/os.py", line 157, in makedirs
mopidy_1         |     mkdir(name, mode)
mopidy_1         | OSError: [Errno 13] Permission denied: '/music/mopidy'
```

Any idea?
